image: maven:3.6-jdk-11

stages:
  - build
  - test
  - deploy
build-java:
  stage: build
  tags:
    - ci
  script:
    - cd CLEA-lib/java
    # build all (for other phase such as docker) but skip tests
    - mvn -DskipTests=true package
  artifacts:
    paths:
      - CLEA-lib/java/target/*.jar

build-c:
  stage: build
  tags:
    - ci
  image: debian:latest
  before_script:
    - apt-get update
    - apt-get install -y -qq cmake make gcc git
  script:
    - cd CLEA-lib/c
    - mkdir build && cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - CLEA-lib/c/build/test_*
      - CLEA-lib/c/build/build_clea

test-java:
  stage: test
  tags:
    - ci
  script:
    - cd CLEA-lib/java
    - mvn verify
  artifacts:
    paths:
      - CLEA-lib/java/target/*.jar

test-interop:
  stage: test
  tags:
    - ci
  image: python:3-buster
  before_script: 
    - apt-get update
    - apt-get install -y -qq openjdk-11-jre
  script:
    - cd CLEA-lib/test
    - python test_clea.py

deploy:
  stage: deploy
  tags:
    - ci
  script:
    - cd CLEA-lib/java
    - mvn $MAVEN_CLI_OPTS -DskipTests=true  -DnexusReleasesUrl=$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/maven -DnexusSnapshotsUrl=$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/maven -s ../../.gitlab-ci/ci_settings.xml deploy
  only:
    - master
    - tags

test-js:
  stage: test
  before_script:
    #Install  node and npm #
    - apt-get install -y curl && curl -sL https://deb.nodesource.com/setup_15.x | bash - && apt-get install -y nodejs && curl -L https://www.npmjs.com/install.sh | sh 
    #Install Latest Google chrome package on system for front test#
    - apt-get install -y chromium
    #Install Latest firefox package on system for front test#
    - apt-get install -y firefox-esr
  tags:
    - ci
  script:
    - cd CLEA-lib/js
    - pwd || true
    - cp ../java/target/clea-crypto-*-jar-with-dependencies.jar ./clea-crypto.jar
    - java -cp ./clea-crypto.jar fr.inria.clea.lsp.LspEncoderDecoder decode || true
    - export CHROME_BIN=chromium
    - export FIREFOX_BIN=firefox-esr
    - npm install
    - npm test
    - npm run testcrypto

build-js:
  stage: build
  image: node:15.13.0
  tags:
    - ci
  script:
    - cd CLEA-lib/js
    - npm install
    - npm run build
    - ls dist
 
