image: maven:3.6-jdk-11

stages:
  - build
  - deploy
  - buildjs

build:
  stage: build
  tags:
    - ci
  script:
    - cd CLEA-lib/java
    # build all (for other phase such as docker) but skip tests
    - mvn -DskipTests=true package
  artifacts:
    paths:
      - CLEA-lib/java/target/*.jar

test:
  stage: build
  tags:
    - ci
  script:
    - cd CLEA-lib/java
    - mvn verify
  artifacts:
    paths:
      - CLEA-lib/java/target/*.jar

deploy:
  stage: deploy
  tags:
    - ci
  script:
    - cd CLEA-lib/java
    - mvn $MAVEN_CLI_OPTS -DskipTests=true  -DnexusReleasesUrl=$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/maven -DnexusSnapshotsUrl=$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/maven -s ../../.gitlab-ci/ci_settings.xml deploy
  only:
    - master
    - tags

buildjs:
  stage: buildjs
  image: node:15.13.0
  tags:
    - ci
  script:
    - cd CLEA-lib/js
    - npm run build
    - ls dist
 
