image: maven:3.6-jdk-11

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - ci
  script:
    - cd java
    # build all (for other phase such as docker) but skip tests
    - mvn -DskipTests=true package
  artifacts:
    paths:
      - java/target/*.jar

test:
  stage: build
  tags:
    - ci
  script:
    - cd java
    - mvn verify
  artifacts:
    paths:
      - java/target/*.jar

deploy:
  stage: deploy
  tags:
    - ci
  script:
    - cd java
    - mvn $MAVEN_CLI_OPTS -DskipTests=true  -DnexusReleasesUrl=$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/maven -DnexusSnapshotsUrl=$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/maven -s ../.gitlab-ci/ci_settings.xml deploy
  only:
    - master
    - tags
